//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int ID { get; set; }
        public int Brand { get; set; }
        public string Model { get; set; }
        public string Color { get; set; }
        public int HP { get; set; }
    
        public virtual Brand Brand1 { get; set; }
    }
}
